In [2]:
import numpy as np

In [3]:
#1. Create a vector with values ranging from 10 to 49.
vec = np.arange(10,50,1)

In [10]:
#2. Create a 3x3 matrix with values ranging from 0 to 8.
mat33 = np.arange(9).reshape(3, 3)

In [20]:
#3. Create a 3x3 identity matrix.
i33 = np.eye(3,dtype=int)

In [19]:
#4. Create a 3x3x3 array with random values.
v333 = np.random.rand(3, 3, 3)

In [69]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
a1010 = np.random.rand(10,10)
print(f'The maximum of the matrix is {a1010.max()}')
print(f'The minimum of the matrix is {a1010.min()}')

The maximum of the matrix is 0.9897397422735263
The minimum of the matrix is 0.004058971134705436


In [28]:
#6. Create a random vector of size 30 and find the mean value.
v30 = np.random.rand(30)
v30.mean()

0.4725593911585094

In [30]:
#7. Normalize a 5x5 random matrix.
a55 = np.random.rand(5,5)
# Find the minimum and maximum values
a55_min, a55_max = a55.min(), a55.max()
# Normalize the matrix using Min-Max scaling
a55_normalized = (a55 - a55_min) / (a55_max - a55_min)

In [35]:
#8. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).
m53 = np.arange(15).reshape(5,3)
m32 = np.arange(6).reshape(3,2)
np.dot(m53,m32) #or m53 @ m32

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [38]:
#9. Create two 3x3 matrices and compute their dot product.
m33 = np.arange(9).reshape(3,3)
mm33 = np.arange(9,18).reshape(3,3)
m33 @ mm33

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [46]:
#10. Given a 4x4 matrix, find its transpose.  
m44 = np.random.rand(4,4)
print(f'Given a 4x4 matrix : {m44}') #Given a 4x4 matrix 
print('------------------')
print(f'Its transpose: {m44.T}')  #its transpose

Given a 4x4 matrix : [[0.31685992 0.882229   0.61025101 0.31254836]
 [0.11352003 0.02427011 0.43618509 0.18677391]
 [0.06004737 0.81248347 0.34210113 0.32434871]
 [0.31560195 0.49208944 0.08945557 0.25377617]]
------------------
Its transpose: [[0.31685992 0.11352003 0.06004737 0.31560195]
 [0.882229   0.02427011 0.81248347 0.49208944]
 [0.61025101 0.43618509 0.34210113 0.08945557]
 [0.31254836 0.18677391 0.32434871 0.25377617]]


In [53]:
#11. Create a 3x3 matrix and calculate its determinant. 
m33 = np.random.randint(1, 10, (3, 3)) 
print("Matrix:\n", m33)
print("Determinant:", np.linalg.det(m33))

Matrix:
 [[7 7 4]
 [5 9 2]
 [8 5 5]]
Determinant: -5.999999999999997


In [57]:
#12. Create two matrices \( A \) (3x4) and \( B \) (4x3), and compute the matrix product \( A \cdot B \).  
A = np.random.randint(1, 10, (3, 4)) # A(3x4)matrix
B = np.random.randint(1, 10, (4, 3)) # B(4x3)matrix
print('A matrix:\n',A)
print('B matrix:\n',B)
print('The matrix product of A and B is:\n',A @ B)

A matrix:
 [[1 5 5 3]
 [6 6 5 8]
 [4 1 9 1]]
B matrix:
 [[8 2 1]
 [6 1 8]
 [7 1 9]
 [5 3 7]]
The matrix product of A and B is:
 [[ 88  21 107]
 [159  47 155]
 [106  21 100]]


In [65]:
#13. Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product. 
m33 = np.random.randint(1, 10, (3, 3)) 
v3 = np.random.randint(1, 10, (3,1))
print('3x3 random matrix:\n',m33)
print('3-element column vector:\n',v3)
print('matrix-vector product:\n',m33 @ v3)

3x3 random matrix:
 [[6 8 1]
 [8 8 9]
 [8 5 8]]
3-element column vector:
 [[4]
 [2]
 [6]]
matrix-vector product:
 [[ 46]
 [102]
 [ 90]]


In [3]:
#14. Solve the linear system \( Ax = b \) where \( A \) is a 3x3 matrix, and \( b \) is a 3x1 column vector.  
A = np.random.randint(1, 10, (3, 3)) # A(3x3)matrix
b = np.random.randint(1, 10, (3,1)) #b(3x1) vector
x = np.linalg.solve(A,b)
print('A matrix:\n',A)
print('b vector:\n',b)
print('The solution:\n',x)

A matrix:
 [[6 8 3]
 [1 9 1]
 [2 5 8]]
b vector:
 [[5]
 [5]
 [4]]
The solution:
 [[0.04444444]
 [0.53333333]
 [0.15555556]]


In [67]:
#15. Given a 5x5 matrix, find the row-wise and column-wise sums.
m55 = np.random.randint(1, 10, (5, 5)) # m55(5x5)matrix
print('5x5 matrix:\n',m55)
print('Row-wise sum:\n',m55.sum(axis=1))
print('Column-wise sum:\n',m55.sum(axis=0))


5x5 matrix:
 [[6 8 4 6 1]
 [7 5 9 8 5]
 [3 4 5 4 3]
 [8 7 7 8 7]
 [6 4 7 4 8]]
Row-wise sum:
 [25 34 19 37 29]
Column-wise sum:
 [30 28 32 30 24]
